---
title: "Address Term 2023"
author: "Soobin Choi"
date: "2023-05-01"
output: 
  github_document: 
    toc: TRUE
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo=TRUE, include=TRUE, comment="")
library(tidyverse)
library(dplyr)
library(ggplot2)
```

# Data Processing

```{r}
original <- read_csv("data/original_full.csv")
rank_sent <- read_csv("data/rank_sent.csv")
brobruh <- read_csv("data/brobruh.csv")

head(original)
head(rank_sent)
head(brobruh)
```

```{r}
# remove NAs in AT-EVER-USE and AGE column
original1 <- original %>% 
  rename(`RESP-ID` = ResponseId) %>% 
  rename(ATUSE = `AT-EVER-USE`) %>% 
  filter(!is.na(ATUSE) & !is.na(AGE))

# remove 'other' genders and move columns for better looking
original2 <- original1 %>% 
  mutate(`RESP-GENDER` = str_to_title(`RESP-GENDER`),
         `ADDR-GENDER` = str_to_title(`ADDR-GENDER`)) %>%
  filter(`RESP-GENDER` %in% c("Feminine", "Masculine", "Non-Binary")) %>% 
  relocate(`ADDR-GENDER`, .after="RESP-GENDER")

```


Since it is hard to make plots when each rank is column, I need to change each column into value.

```{r}

# test if it works
toy_df <- head(original2, 20)

toy_df %>% 
  pivot_longer(c("PARENTS", "SIBLING", "PARTNER", "COWORKER", "BOSS", "FRIEND", "STRANGER"), names_to = "ADDR-RANK", values_to = "FREQUENCY")


# good to go
original2 %>% 
  pivot_longer(c("PARENTS", "SIBLING", "PARTNER", "COWORKER", "BOSS", "FRIEND", "STRANGER"), names_to = "ADDR-RANK", values_to = "FREQUENCY")
```


```{r}
# check the categories in AGE column
original2 %>% 
  select(AGE) %>% 
  unique()

# incorporate 'Over 70' to '56-70' + convert columns into values
org_clean <- original2 %>% 
  mutate_all(funs(str_replace_all(., "56-70", "Over 70"))) %>% 
  mutate_all(funs(str_replace_all(., "Over 70", "56-Over 70"))) %>% 
  pivot_longer(c("PARENTS", "SIBLING", "PARTNER", "COWORKER", "BOSS", "FRIEND", "STRANGER"), names_to = "ADDR-RANK", values_to = "FREQUENCY") %>% 
  select(-`GENDER-4-TEXT`) %>% 
  mutate(FREQUENCY = as.numeric(FREQUENCY))

```

Okay, I have left with 26,439 values in total.


# Analysis & Plots

## The usage of *DUDE* by gender and age

```{r}
# sort 'dude' only
dude_df <- org_clean %>% 
  filter(grepl("dude", org_clean$ATUSE) == TRUE)


# check the count of each age category
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  na.omit(AGE) %>% 
  group_by(AGE, `ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`))

# Count of each resp-gender category

dude_df %>% 
  group_by(`RESP-GENDER`) %>% 
  summarise(n = n_distinct(`RESP-ID`))


dude_df %>% 
  filter(TERM == "DUDE")

# Plot - Dude Usage by gender and age - non-binary excluded

dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(AGE, `ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`)) %>% 
  ggplot(aes(x = `ADDR-GENDER`, y = Count, fill = `RESP-GENDER`)) +
  facet_wrap(vars(AGE), ncol = 4) + 
  geom_col(position = "dodge") + 
  labs(title = "Dude Usage by gender and age - non-binary excluded")




# 이거를 퍼센티지로 표현해야 할 것 같은데..
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(AGE, `ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`)) %>% 
  unite(Gender, `RESP-GENDER`, `ADDR-GENDER`) %>% 
  show
```


```{r}

'
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(AGE, `ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(count = n_distinct(`RESP-ID`)) %>% 
  unite(Gender, `RESP-GENDER`, `ADDR-GENDER`) %>% 
  ggplot(aes(x = AGE, weight = count, fill = Gender)) +
  geom_bar(position = "dodge")
'

# Plot - dodge barplot
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(AGE, `ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(count = n_distinct(`RESP-ID`)) %>% 
  unite(Gender, `RESP-GENDER`, `ADDR-GENDER`) %>% 
  ggplot(aes(x = AGE, y = count, fill = Gender)) +
  geom_col(position = "dodge") + 
  geom_text(aes(label = count), position = position_dodge(1), vjust = -0.7) +
  ylim(0, 105)
```



```{r}
# Dude usage, WITHOUT considering age category

dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(`ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`)) %>% 
  ggplot(aes(x = `ADDR-GENDER`, y = Count, fill = `RESP-GENDER`)) +
  geom_col(position = "dodge") + 
  labs(title = "Dude Usage by gender - non-binary excluded")
  
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  na.omit(FREQUENCY) %>% 
  group_by(`ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(mean_freq = mean(FREQUENCY)) %>% 
  ggplot(aes(x = `RESP-GENDER`, y = mean_freq, col = `ADDR-GENDER`, group = `ADDR-GENDER`))+
  geom_point() + 
  geom_text(aes(label = round(mean_freq, 2), vjust = -0.5, nudge_y = 0.1)) +
  geom_path() +
  ylim(1.9, 2.6)
```

## Use of dude by Gender of Speaker and Addressee (2023)

```{r}
# Plot
dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(`ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`)) %>% 
  ggplot(aes(x = `ADDR-GENDER`, y = Count, fill = `RESP-GENDER`)) +
  geom_col(position = "dodge") + 
  labs(title = "Dude Usage by gender - non-binary excluded")

# Table

dude_df %>% 
  filter(TERM == "DUDE" & `RESP-GENDER` != "Non-Binary") %>% 
  group_by(`ADDR-GENDER`, `RESP-GENDER`) %>% 
  summarise(Count = n_distinct(`RESP-ID`)) %>% 
  show()
```


## The usage of *dude* and *bro* by gender - non-binary exclusive

```{r}
# sort people who use dude and/or bro

dudebro <- org_clean %>% 
  filter(grepl("dude", org_clean$ATUSE) == TRUE | grepl("bro", org_clean$ATUSE) == TRUE)
  

```

```{r}
dudebro %>% 
  select(`RESP-GENDER`, `ADDR-GENDER`) %>% 
  unique()
```


```{r}
# plot - dude/bro usage by rank and gender

dudebro %>% 
  filter(TERM %in% c("DUDE", "BRO"), `RESP-GENDER` != c("Non-Binary")) %>% 
  group_by(`RESP-GENDER`, `ADDR-GENDER`, TERM, `ADDR-RANK`) %>% 
  summarise(mean_freq = mean(as.numeric(FREQUENCY), na.rm = TRUE)) %>% 
  ggplot(aes(x = `ADDR-RANK`, y = mean_freq,  group = TERM, col = TERM)) +
  facet_wrap(`ADDR-GENDER`~`RESP-GENDER`, ncol = 1, strip.position = "right", 
             labeller = labeller(
               `ADDR-GENDER` = c(`Feminine`="Addr_F", `Masculine`="Addr_M"),
               `RESP-GENDER` = c(`Feminine`="Resp_F", `Masculine`="Resp_M"))) + 
  geom_line() +
  geom_point() + 
  scale_y_continuous(limits = c(0, 4)) +
  labs(title = "Compare dude/bro based on interlocutors' gender (non-binary exclusive)", x = 'Relationship')
  

dudebro %>% 
  filter(TERM %in% c("DUDE", "BRO") & `RESP-GENDER` %in% c("Feminine", "Masculine") & `ADDR-GENDER` %in% c("FEMININE", "MASCULINE")) %>% 
  group_by(`RESP-GENDER`, `ADDR-GENDER`, TERM, `ADDR-RANK`) %>% 
  summarise(mean_freq = mean(FREQUENCY, na.rm = TRUE))
```

## Is there any difference in the usage of *dude* by race?

```{r}
org_clean %>% 
  mutate(RACE = str_to_title(RACE)) %>% 
  group_by(RACE) %>% 
  summarize(n = n_distinct(`RESP-ID`))
```













